config:
  send_anonymous_usage_stats: False

default:
  outputs:

    dev: Krish@1998
      type: snowflake
      account: bub70851.us-east-1
      user: DBT_CLOUD_DEV
      password: Krish@1998
      role: TRANSFORMER_DEV
      database: DEV
      warehouse: TRANSFORMING
      schema: dbt_jkm
      threads: 2
      client_session_keep_alive: False

  target: dev
